name: Build and Release Pipeline

on:
  push:
    branches: [ "main" ]
    tags: '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base Docker image
        run: |
          docker build -t papauorg/sugar-dispenser:base -f .devcontainer/Dockerfile .

      - name: Run build script in final image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace papauorg/sugar-dispenser:base bash -c "./.devcontainer/installLibraries.sh && ./build.sh"

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          name: Release ${{ steps.tag.outputs.TAG_NAME }}
          files: ./output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
